version: "2.1"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: ["8080:8080"]
    expose:
      - 8080
  books_db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_db
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: