version: "2.1"

services:
  app:
    image: 127.0.0.1:8080
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: ["8080:8080"]
  books_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "bookdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "Paard1234!"
      POSTGRES_ROOT_PASSWORD: "Paard1234!"
    ports: ["5432:5432"]